- type: entity
  name: ящик для наручників
  parent: BoxCardboard
  id: BoxHandcuff
  description: Ящик, повний наручників.
  components:
  - type: StorageFill
    contents:
      - id: Handcuffs
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: handcuff

- type: entity
  name: коробка світлошумових
  parent: BoxCardboard
  id: BoxFlashbang
  description: 'ПОПЕРЕДЖЕННЯ: Ці пристрої надзвичайно небезпечні та можуть спричинити сліпоту або глухоту при повторному використанні.'
  components:
  - type: StorageFill
    contents:
      - id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: flashbang

- type: entity
  name: коробка секхудів
  parent: BoxCardboard
  id: BoxSechud
  description: Коробка секхудів
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesHudSecurity
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: sechud

- type: entity
  name: ziptie box
  parent: BoxCardboard
  id: BoxZiptie
  description: A box full of zipties.
  components:
  - type: Storage
    grid:
    - 0,0,4,3
    whitelist:
      components:
      - Handcuff
  - type: StorageFill
    contents:
      - id: Zipties
        amount: 10
  - type: Sprite
    layers:
      - state: box_security
      - state: ziptie

- type: entity
  name: forensic pad box
  parent: BoxCardboard
  id: BoxForensicPad
  description: A box of forensic pads.
  components:
  - type: Storage
    grid:
    - 0,0,4,3
  - type: StorageFill
    contents:
      - id: ForensicPad
        amount: 10
  - type: Sprite
    layers:
      - state: box_security
      - state: forensic
