- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Frontier
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster
# - Core
#  - Europa
# - Fland
  - Kettle
  - Marathon
  - Meta
  - Omega
  - Origin
  - Packed
  - Saltern
