- type: entity
  id: EngineeringTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: інженерний-техфаб плата машини
  description: Машинна друкована плата для інженерного-техфабу
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: EngineeringTechFab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker
    - type: StaticPrice
      price: 500

- type: entity
  id: ServiceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: сервіс-техфаб плата машини
  description: Машинна друкована плата для сервісного-техфабу
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ServiceTechFab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker
    - type: StaticPrice
      price: 500

- type: entity
  id: ScienceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: науковий-техфаб плата машини
  description: Машинна друкована плата для наукового-техфабу
  components:
    - type: Sprite
      state: science
    - type: MachineBoard
      prototype: ScienceTechFab
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker
    - type: StaticPrice
      price: 500