- type: entity
  id: CrateServiceReplacementColoredLights
  name: Ящик з кольоровими вогнями
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxColoredLighttube
        amount: 2
